reset:
  rm -f db.sqlite

fill:
  sqlite3 db.sqlite ".read fake_dump.sql"

regenerate:
  mkdir -p static/day
  for date in $(sqlite3 db.sqlite "SELECT DISTINCT substr(hour, 1, 10) FROM hourly_readings;"); do \
    sqlite3 db.sqlite "SELECT json_group_array(json_object( \
      'hour', hour, \
      'temperature', temperature, \
      'humidity', humidity, \
      'wind_speed', wind_speed, \
      'wind_direction', wind_direction, \
      'luminosity', luminosity, \
      'rainfall', rainfall \
    )) FROM hourly_readings WHERE hour LIKE '${date}%' ORDER BY hour;" > "static/day/${date}.json"; \
    echo "Generated static/day/${date}.json"; \
  done
